data:extend({
	-- White sprites
	{
		type = "sprite",
		name = "plc-play-button-white",
		filename = "__SignalController__/graphics/sprites/play_white.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-pause-button-white",
		filename = "__SignalController__/graphics/sprites/pause_white.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-up-button-white",
		filename = "__SignalController__/graphics/sprites/up_white.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-down-button-white",
		filename = "__SignalController__/graphics/sprites/down_white.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-trash-button-white",
		filename = "__SignalController__/graphics/sprites/trash_white.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	-- Black sprites
	{
		type = "sprite",
		name = "plc-play-button-black",
		filename = "__SignalController__/graphics/sprites/play_black.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-pause-button-black",
		filename = "__SignalController__/graphics/sprites/pause_black.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-up-button-black",
		filename = "__SignalController__/graphics/sprites/up_black.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-down-button-black",
		filename = "__SignalController__/graphics/sprites/down_black.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},
	{
		type = "sprite",
		name = "plc-trash-button-black",
		filename = "__SignalController__/graphics/sprites/trash_black.png",
		priority = "extra-high-no-scale",
		width = 32,
		height = 32,
	},

})
